export { default as IconGithub } from './github';
export { default as IconTwitter } from './twitter';
export { default as IconDiscord } from './discord';
export { default as IconGoogle } from './google';
export { default as IconBack } from './back';
export { default as IconCross } from './cross';
export { default as IconArrowLeft } from './arrow-left';
export { default as IconArrowRight } from './arrow-right';
export { default as IconPrism } from './prism';
export { default as IconKibisis } from './kibisis';
export { default as IconPera } from './pera';
export { default as IconLogout } from './logout';
export { default as IconMail } from './mail'
export { default as IconCheck } from './check'
export { default as IconSignOut } from './sign-out'
export { default as IconClient } from './client'
export { default as IconSun } from './sun'
export { default as IconMoon } from './moon'